name = "OpenRouter"
uuid = "b1229eab-bc7b-489c-92b5-04baf87d8d0b"
version = "1.0.0"
authors = ["SixZero <havliktomi@hotmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[compat]
Aqua = "0.8"
Dates = "1.11.0"
HTTP = "1"
julia = "1.11"
JSON3 = "1"
PrecompileTools = "1"
Scratch = "1.3.0"
Test = "1"

[targets]
test = ["Aqua", "Test"]
